config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  
  root :to => 'homes#top'
  
  resources :posts do
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
    collection do
      get 'confirm'
      get :rankings
    end
  end

  resources :users, only:[:index, :show, :edit, :update] do
    resources :messages, only: [:create]
    resources :rooms, only: [:index, :create, :show]    
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :rooms, only: [:create, :show] do
    resources :messages, only: [:create, :destroy] 
  end
  
end

app/models/post.rb
class Post < ApplicationRecord

  attachment :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :battle_type, presence: true, length: { maximum: 20 }
  validates :game_recode, presence: true, length: { maximum: 1000 }
  validates :text, presence: true, length: { maximum: 1000 }

  enum status: { published: 0, draft: 1 }

    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @posts = Post.published.page(params[:page]).per(9).reverse_order
    if params[:search].present? 
      @posts = @posts.where('battle_type LIKE ?', "%#{params[:search]}%")
    end

    words_count = Hash.new(0)
    Post.where(status: 'published').pluck(:battle_type).each do |battle_type|
      battle_type.split("VS").each do |word|
        word.strip!
        words_count[word] += 1 unless word.empty?
      end
    end
    @rankings = words_count.sort_by { |_, count| -count }.first(5).to_h
  end

  def show 
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.page(params[:page]).per(4).reverse_order
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end
  
  def confirm
    @posts = current_user.posts.draft.page(params[:page]).per(8).reverse_order
  end

  def rankings
    @rankings = Post.where(status: 'published').group(:battle_type).order('count_all DESC').limit(3).count
  end

  private
  def post_params
    params.require(:post).permit(:game_recode, :text, :battle_type, :image, :user_id, :status)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_index.html.erb
<div class="posts"> 
  <% if @posts.any? %>
    <div class="row mt-5 index-left w-100">
      <% posts.each do |post| %>
        <div class="one-post col-md-3 mb-3 post-content">
          <%= link_to post_path(post) do %>
            <p class="caption"><%= post.user.name %></p>
            <%= attachment_image_tag post, :image, format: 'jpeg', size: '300x200' %>
            <p class="caption"><%= post.battle_type %></p>
            <p class="caption"><%= "#{post.comments.count} コメント" %></p>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= paginate posts %>
  <% else %> 
    <p class="no-results">一致する検索結果がありません</p> 
  <% end %> 
</div>

app/views/posts/confirm.html.erb
<div class="cover-index drafts-page">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">下書き一覧</h1>
    </div>
    <%= render 'index', posts: @posts %>
  </div>
</div>

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>棋譜投稿一覧</title>
  </style>
  <%= stylesheet_link_tag 'posts', media: 'all' %>
</head>
<body>
<div class="cover-edit">
  <div class="container">
    <div class="row">
      <h1 class="font-weight-normal mt-5 mb-5 center-title">棋譜投稿編集</h1>
    </div>
    <% if @post.errors.any? %>
    <div class="card text-center text-white bg-danger mb-3">
      <%= @post.errors.count %>件のエラーが発生しました
      <% @post.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
      </div>
    <% end %>
    <div class="row">
      <%= form_with model: @post, local:true do |f| %>
      <div class="form-group mb-3">
        <label class="form-label">戦型</label>
        <%= f.text_field :battle_type, class: "form-control" %>
      </div>
      <div class="form-group mb-3">
        <label class="form-label">棋譜</label>
        <%= f.text_area :game_recode, rows: 10, class: "form-control" %>
      </div>
      <div class="form-group mb-4">
        <label class="form-label">感想</label><br>
        <%= f.text_area :text, rows: 10, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.select :status, Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"),k]}, {}, {class: "custom-select w-25 mb-3"} %>
      </div>
      <%= f.submit '保存する', class: "btn btn-success" %><br>
      <%= link_to '投稿詳細ページへ', post_path(@post), class: "btn btn-dark mt-3" %>
      <% end %>
    </div>
  </div>
</div>
</body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>棋譜投稿一覧</title>
  <%= stylesheet_link_tag 'posts', media: 'all' %>
</head>
<body>
<div class="cover-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">棋譜投稿一覧</h1>
    </div>
    
    <div class="row mt-0 mb-0 align-self-end">
      <%= form_with url: posts_path, method: :get, local: true, html: { class: 'search-form' } do |f| %>
        <%= f.text_field :search %>
        <%= f.submit '検索する', name: nil %>
      <% end %>
    </div>
    
    <!-- スマホ用ランキング（表示切り替え付き） -->
    <% if @rankings && !@rankings.empty? %>
      <div class="ranking-container d-sm-none">
        <button id="toggle-button-sp" class="ranking-button">人気戦型ランキング</button>
        <div class="ranking-list" id="ranking-list-sp" style="display: none;">
          <% @rankings.each_with_index do |(battle_type, count), index| %>
            <p class="ranking-item"><%= "#{index + 1}位  #{battle_type}: #{count}件" %></p>
          <% end %>
        </div>
      </div>
    <% end %>
    
    <div class="main-content">
      <div class="posts row">
        <%= render 'index', posts: @posts %>
      </div>
      
      <div class="sidebar d-none d-sm-block">
        <% if @rankings && !@rankings.empty? %>
          <div class="ranking-container"> 
            <button id="toggle-button" class="ranking-button">人気戦型ランキング</button>
          </div>
          <div class="ranking-list" id="ranking-list" style="display: none;">
            <% @rankings.each_with_index do |(battle_type, count), index| %>
              <p class="ranking-item"><%= "#{index + 1}位  #{battle_type}: #{count}件" %></p>
            <% end %>
          </div>
        <% else %>
          <p>ランキングが存在しません。</p>
        <% end %>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/posts/new.html.erb
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>新規棋譜投稿</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div class="cover-new">
    <div class="container d-flex flex-column align-items-center">
      <div class="row mt-5">
        <h1 class="font-weight-normal">新規棋譜投稿</h1>
      </div>
      <% if @post.errors.any? %>
      <div class="card text-center text-white bg-danger mt-3 d-flex flex-column custom-error-box">
        <div class="error-message">
          <%= @post.errors.count %>件のエラーが発生しました
          <% @post.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        </div>
      </div>
      <% end %>
      <div class="row mt-5">
        <%= form_with model: @post, local:true do |f| %>
        <div class="form-group mb-3">
          <label class="form-label">【戦型】</label>
          <%= f.text_field :battle_type, class: "form-control" %>
        </div>
        <div class="form-group mb-3">
          <label class="form-label">【棋譜】</label>
          <%=f.text_area :game_recode, rows: 17, class: "form-control" %>
        </div>
        <div class="form-group mb-3">
          <label class="form-label">【感想】</label>
          <%=f.text_area :text, rows: 3, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.select :status, Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"),k]}, {}, {class: "custom-select mb-3"} %>
        </div>
          <%= f.submit '投稿する', class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/posts/rankings.html.erb
<div class="cover-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">戦型ランキング</h1>
    </div>
    <div class="row">
      <div class="col-md-8">
        <ol>
          <% @rankings.each do |battle_type, count| %>
            <li><%= "#{battle_type}: #{count}件" %></li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="cover-show">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-1 mb-1">
      <h1 class="font-weight-normal mt-5 mb-0">棋譜投稿詳細</h1>
    </div>
    <% if @comment.errors.any? %>
    <div class="card text-center text-white bg-danger mt-5">
      <%= @comment.errors.count %>件のエラーが発生しました
      <% @comment.errors.full_messages.each do |message| %>
       <%= message %>
      <% end %>
    </div>
    <% end %>
    <div class="container d-flex mt-5">
      <div class="d-block">
        <p class="caption"><%= @post.user.name %></p>
        <%= attachment_image_tag @post, :image, format: 'jpeg', size: "450x350" %><br>
        <h2>戦型</h2>
        <p class="caption"><%= @post.battle_type%>
          <% if @post.favorited_by?(current_user) %>
          <%= link_to post_favorites_path(@post),  data: { turbo_method: :delete }, class: "favorite_btn" do %>
          ♥<%= @post.favorites.count %> いいね
          <% end %>
          <% else %>
          <%= link_to post_favorites_path(@post),  data: { turbo_method: :post }, class: "favorite_btn" do %>
            ♡<%= @post.favorites.count %> いいね
          <% end %>
          <% end %>
        </p>
        <h2>棋譜</h2>
        <p id="text"><%= @post.game_recode %></p>
        <h2>感想</h2>
        <p id="text"><%= @post.text %></p>
    <% if @post.user == current_user %>
      <div class="btn-group-vertical">
        <%= link_to '編集する', edit_post_path(@post.id), class: "btn btn-info mr-3" %>
        <%= link_to '削除する', post_path(@post.id),  data: { turbo_method: :delete, turbo_confirm:  "本当に消しますか？"}, class: "btn btn-danger" %>
      </div>
        <% end %>  
        <%= link_to '投稿一覧ページへ', posts_path, class: "btn btn-dark mt-3" %>
      </div>
      
      <div class="comments ml-5 mt-5">
        <%= form_with(model:[@post, @comment], local: true) do |f| %>
        <div class="d-flex align-items-start">
        <%= f.text_area :comment, :size=>"60x3",placeholder: "コメントする" %>
        <%= f.submit "送信する", class: "btn btn-success mb-4" %>
        </div>
        <% end %>

        <p>コメント件数：<%= @comments.count %></p>
        <% @comments.each do |comment| %>
          <div class="comments-index mb-2">
            <%= comment.user.name %>
            <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %><br>
            <div class="d-flex">
              <%= comment.comment %>
              <% if comment.user == current_user %>
                <div class="comment-delete">
                  <%= link_to "削除", post_comment_path(comment.post, comment), data: { turbo_method: :delete }, class: "btn-sm btn-danger" %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
        <%= paginate @comments %>
      </div>
    </div>
  </div>
</div>