config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  
  root :to => 'homes#top'
  
  resources :posts do
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
    collection do
      get 'confirm'
      get :rankings
    end
  end

  resources :users, only:[:index, :show, :edit, :update] do
    resources :messages, only: [:create]
    resources :rooms, only: [:index, :create, :show]    
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :rooms, only: [:create, :show] do
    resources :messages, only: [:create, :destroy] 
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :comment, presence: true, length: { maximum: 35 }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/post.rb
class Post < ApplicationRecord

  attachment :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :battle_type, presence: true, length: { maximum: 20 }
  validates :game_recode, presence: true, length: { maximum: 1000 }
  validates :text, presence: true, length: { maximum: 1000 }

  enum status: { published: 0, draft: 1 }

    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  attachment :profile_image

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  validates :name, presence: true

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @posts = Post.published.page(params[:page]).per(9).reverse_order
    if params[:search].present? 
      @posts = @posts.where('battle_type LIKE ?', "%#{params[:search]}%")
    end

    words_count = Hash.new(0)
    Post.where(status: 'published').pluck(:battle_type).each do |battle_type|
      battle_type.split("VS").each do |word|
        word.strip!
        words_count[word] += 1 unless word.empty?
      end
    end
    @rankings = words_count.sort_by { |_, count| -count }.first(5).to_h
  end

  def show 
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.page(params[:page]).per(4).reverse_order
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end
  
  def confirm
    @posts = current_user.posts.draft.page(params[:page]).per(8).reverse_order
  end

  def rankings
    @rankings = Post.where(status: 'published').group(:battle_type).order('count_all DESC').limit(3).count
  end

  private
  def post_params
    params.require(:post).permit(:game_recode, :text, :battle_type, :image, :user_id, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/proverbs_helper.rb
module ProverbsHelper
  def daily_proverb
    ::PROVERBS[Date.today.day % ::PROVERBS.size]
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shogi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if user_signed_in? %> 
    <header>
    <!-- ハンバーガーメニュー -->
      <div class="menu-container">
        <button id="menu-toggle" class="menu-button">
          <span class="bar"></span>
          <span class="bar"></span>
          <span class="bar"></span>
        </button>
        <nav id="menu" class="menu hidden">
         <ul>
          <li><%= link_to "トップ", root_path, class: "text-white nav-link" %></li>
          <li><%= link_to "投稿する", new_post_path, class: "text-white nav-link" %></li>
          <li><%= link_to "投稿一覧", posts_path, class: "text-white nav-link" %></li>
          <li><%= link_to "下書き一覧", confirm_posts_path, class: "text-white nav-link" %></li>
          <li><%= link_to "ユーザ一覧", users_path, class: "text-white nav-link" %></li>
          <li><%= link_to "マイページ", user_path(current_user.id), class: "text-white nav-link" %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "text-white nav-link" %></li>
         </ul>
        </nav>
     </div>

    <!-- 通常のメニュー（PC用） -->
      <nav class="pc-nav">
        <div><%= link_to root_path, class: "text-white nav-link" do %>shogi player<% end %></div>
        <%= link_to "トップ", root_path, class: "text-white nav-link" %>
        <%= link_to "投稿する", new_post_path, class: "text-white nav-link" %>
        <%= link_to "投稿一覧", posts_path, class: "text-white nav-link" %>
        <%= link_to "下書き一覧", confirm_posts_path, class: "text-white nav-link" %>
        <%= link_to "ユーザ一覧", users_path, class: "text-white nav-link" %>
        <%= link_to "マイページ", user_path(current_user.id), class: "text-white nav-link" %>
        <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "text-white nav-link" %>
      </nav>
    </header>
  <% end %>
  <%= yield %>
</body>
</html>